### ISSUE TITLE
migrations on arrow-cpp-feedstock run into timeout while rerendering

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/conda-forge-pinning-feedstock#5815] opened 2024-04-26 19:02 UTC
### Comment:

The pin for aws-crt-cpp was recently updated to 0.26.8 (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5762), which started the [current migration aws_crt_cpp0268](https://conda-forge.org/status/migration/aws_crt_cpp0268). It was successful for tiledb-feedstock (https://github.com/conda-forge/tiledb-feedstock/pull/279), but unfortunately it failed with a rerendering error for [arrow-cpp-feedstock](https://github.com/conda-forge/arrow-cpp-feedstock/pulls?q=is%3Apr+aws_crt_cpp+). This is causing a problem because tiledb-py-feedstock requires tiledb and pyarrow, which currently generates a solver error (https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/92#issuecomment-2079951307).

I've never attempted to troubleshoot a migration error for a feedstock that I don't maintain. As a first step, could someone with sufficient access try to restart the migration? Is there anything I can do to help?

**Comment by xhochy** [comment] 2024-04-26 19:39
The problem is that the rerendering takes longer than 900s. This is a newly added timeout in the bot. We need to make an exception for arrow-cpp in the bot (or wait for the next conda release).

**Comment by jdblischak** [comment] 2024-04-26 19:50
> The problem is that the rerendering takes longer than 900s. This is a newly added timeout in the bot.

Can I manually apply the migration locally and send a PR to arrow-cpp-feedstock? Or would that interfere with the migration?

**Comment by xhochy** [comment] 2024-04-26 20:00
It should solve your problem, but long-term the bot needs the timeout fix.

**Comment by jdblischak** [comment] 2024-04-26 21:14
> It should solve your problem, but long-term the bot needs the timeout fix.

Done in https://github.com/conda-forge/arrow-cpp-feedstock/pull/1375

**Comment by h-vetinari** [comment] 2024-04-29 00:56
> The problem is that the rerendering takes longer than 900s. This is a newly added timeout in the bot.

When did this get added? It's too tight for several feedstocks - IMO it needs to be bumped ASAP. CC @beckermr

Fortunately, a bunch of speedups [landed](https://github.com/conda/conda-build/issues/5224#issuecomment-2077998182) in the upcoming conda-build 24.5, but we don't have that one available yet.

**Comment by beckermr** [comment] 2024-04-29 01:17
That timeout has been in place for several years. I did some refactoring but idk what would have changed to make a difference like this.

**Comment by h-vetinari** [comment] 2024-04-29 01:47
It will effectively break all migrations from working on the arrow-feedstock, which has a disproportionate impact because we have so many deps there that need migrating, as well as 4 maintenance branches. Basically, that feedstock is not workable without the bot opening these PRs, so we need to fix this real soon, as its going to cause logjams in several places otherwise. A timeout exception for arrow is probably the easiest. Or we could let the bot run on an unreleased conda-build (that we could build into a label). Or investigate what recent refactors regressed...

**Comment by beckermr** [comment] 2024-04-29 01:56
The timeout has been there several years and nothing was broken. I honestly don't get what's suddenly changed or regressed.

**Comment by beckermr** [comment] 2024-04-29 02:02
I just checked the pull requests for arrow-feedstock and I cannot find a PR from the bot for several years at least. Maybe I messed up checking?

Otherwise, this matches the fact that the bot has been enforcing a timeout for many years on long rerenders. 

What is suddenly going to break for arrow-feedstock now when it never got prs anyways?

**Comment by h-vetinari** [comment] 2024-04-29 02:40
> I just checked the pull requests for arrow-feedstock and I cannot find a PR from the bot for several years at least.

I don't know how you searched, but we've been [getting](https://github.com/conda-forge/arrow-cpp-feedstock/pulls?q=is%3Apr+author%3Aregro-cf-autotick-bot+is%3Aclosed) 10+ PRs per month. Last one was April 23rd 02:55 UTC.

> I honestly don't get what's suddenly changed or regressed.

Arrow has been getting long rerender times for a while (and once @mbargull got aware of this, he opened https://github.com/conda/conda-build/issues/5224 and tackled some bottlenecks; the result of that is going to show up in conda-build 24.5). It's possible that we were close to the timeout already, and that some minor regression pushed us from, say, ~850sec over 900.

**Comment by beckermr** [comment] 2024-04-29 02:56
Those prs are for arrow-cpp, not arrow. 

You mentioned arrow above, right?

**Comment by beckermr** [comment] 2024-04-29 02:57
> It will effectively break all migrations from working on the arrow-feedstock, which has a disproportionate impact because we have so many deps there that need migrating, as well as 4 maintenance branches. Basically, that feedstock is not workable without the bot opening these PRs,

^ This is what is was responding too.

**Comment by h-vetinari** [comment] 2024-04-29 03:02
Yes, sorry, that was an inaccuracy on my part. There is a (IMO) much less important arrow library for timestamps, but I was referring to [apache/arrow](https://github.com/apache/arrow), the "composable data stack" behemoth that's eating the world (in a nice way), which for us is built on https://github.com/conda-forge/arrow-cpp-feedstock (various libs & python bindings)

**Comment by beckermr** [comment] 2024-04-29 03:22
Ahhhhh that makes more sense.

On the timeout itself, the bot enforces a timeout due to very long rerenders maing it slower than it already is. The 15 minute (=900 second) timeout is an order of magnitude or more longer than the typical feedstock rerendering time. I get that this is frustrating.

However, looking at the arrow-cpp recipe (which I have not spend much time on at all), it appears to be nearly a dozen packages in one. Splitting that feedstock up into more than one would potentially have other benefits in addition to easing the burden on our already overstressed tools.

**Comment by h-vetinari** [comment] 2024-05-03 00:53
> Splitting that feedstock up into more than one would potentially have other benefits in addition to easing the burden on our already overstressed tools.

I opened an RFC for that: https://github.com/conda-forge/arrow-cpp-feedstock/issues/1381

**Comment by xhochy** [comment] 2024-05-11 07:09
Migrations have been coming again for arrow-cpp, so closing this.

**Comment by h-vetinari** [comment] 2024-05-11 11:34
Really, I haven't seen a bot PR yet. All the recent migrations were done by hand.

**Comment by xhochy** [comment] 2024-05-11 15:09
Ah! I only have seen migrations and thought you wanted to see them happen automatically. I'll look into this next week (when I fix the aws-sdk-cpp release)

**Comment by h-vetinari** [comment] 2024-05-14 00:48
It's possible that the performance improvements in conda-build 24.5 unblocked this. There are new PRs for main (much reduced after splitting of pyarrow bits) and v15.x (still big to rerender):
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/1391
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/1392

**Comment by xhochy** [comment] 2024-10-13 07:55
Closing as we reliably get PRs for the feedstock again.

**Closed by xhochy** 2024-10-13 07:55 UTC
Labels: question
