### ISSUE TITLE
Boost=1.72 upgrade

### ISSUE THREAD

**Issue by joeywstorer** [conda-forge/conda-forge-pinning-feedstock#646] opened 2020-06-04 19:52 UTC
Issue:  Incompatibility between packages due to boost=1.70.0  Request upgrade to 1.72

<br/>
Environment (<code>conda list</code>): 

This happens in an attempt to build a Docker container with both Rapids 0.13 and RDKit 2020.03.2  The experts asked me to post this issue to conda-forge.

<details>

```
# packages in environment at /opt/conda/envs/rapids:
boost                     1.70.0           py37h9de70de_1    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : rapids
    active env location : /opt/conda/envs/rapids
            shell level : 1
       user config file : /home/u224361/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/rapidsai/linux-64
                          https://conda.anaconda.org/rapidsai/noarch
                          https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/u224361/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/u224361/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.23.0 CPython/3.7.4 Linux/5.3.0-42-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 4361:4400
             netrc file : None
           offline mode : False


```
</details>

**Comment by isuruf** [comment] 2020-06-04 19:57
Can you please explain the incompatibility?

**Comment by joeywstorer** [comment] 2020-06-04 19:59
RDkit will not install into a docker container with boost=1.70.  RDKit requires boost=1.72.  The Rapids team noted that the version of boost is driven by conda-forge and so asked me to post this issue here, agreeing that an upgrade would probably be a good thing.

**Comment by jakirkham** [comment] 2020-06-04 20:08
I think we had also discussed doing every other Boost version. As we are at 1.70 moving to 1.72 would align with that.

cc @CJ-Wright @beckermr

**Comment by isuruf** [comment] 2020-06-04 20:10
I don't understand either of you. We are in the middle of upgrading to 1.72 and migration is under way.

**Comment by beckermr** [comment] 2020-06-04 20:14
Right, but some other version or ping moved ahead of it. You'll need to go back and rebuild the package with the other pin that moved to match boost 1.70. That would either mean a version of rapids on 1.70 or a version of RDKit on it. IDK which one since I do not know the graph here.

@isuruf I think this is related to the branches for pins CFEP we have been discussing.

**Comment by isuruf** [comment] 2020-06-04 20:17
Well, I asked @joeywstorer about the incompatibility, but @joeywstorer doesn't say what the incompatibility is and has posted a redacted list of packages in the issue I've asked.

Let's not make any assumptions and close this issue if @joeywstorer can't give a reproducer.

**Comment by beckermr** [comment] 2020-06-04 20:18
100% agreed.

**Comment by joeywstorer** [comment] 2020-06-04 20:22
If migration to 1.72 is underway then there is no issue as far as I'm concerned.

**Comment by isuruf** [comment] 2020-06-04 20:23
If you want the migration to go faster, please help out.

**Closed by isuruf** 2020-06-04 20:23 UTC

**Comment by isuruf** [comment] 2020-06-04 20:24
There are currently 12 PRs blocking the migration. You can see them at https://conda-forge.org/status/ . Any help is appreciated.

**Comment by jakirkham** [comment] 2020-06-04 20:39
Oops didn't realize that. Sorry for the noise.
