### ISSUE TITLE
Adding PyPy38

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#2089] opened 2021-11-01 19:51 UTC
Recently [PyPy released support for Python 3.8]( https://www.pypy.org/posts/2021/10/pypy-v736-release.html ). Since we have dropped Python 3.6 support and [NEP 29]( https://numpy.org/neps/nep-0029-deprecation_policy.html ) suggests dropping Python 3.7 on 2021 Dec 26, it seems projects are going to be interested in moving to Python 3.8 soon. Admittedly we will probably hang onto 3.7 longer. Though given the pending demand for moving projects to Python 3.8, am wondering if it is time to start a PyPy38 migration. Thoughts? 🙂

cc @mattip @conda-forge/core

**Comment by mattip** [comment] 2021-11-01 20:30
I am working on two PRs to the PyPy feedstock. https://github.com/conda-forge/pypy3.6-feedstock/pull/69 to add support for the recent OpenSSL3 migration, and https://github.com/conda-forge/pypy3.6-feedstock/pull/61 to build PyPy 3.8 for windows. The status of these is:
- openssl3 builds and passes all but one test on linux, and fails like upstream pypy does on windows.
- pypy3.8 is available for [linux-64 and osx-64](https://anaconda.org/conda-forge/pypy3.8/files). The hold up was adding the dll-directory handling in python3.8+, now it is a matter of making the bld.bat work for both 3.7 and 3.8.

Which should I finish first: openssl3 (with a functional-but-fails-edge-cases-on-windows version) or the pypy3.8-windows?

**Comment by isuruf** [comment] 2021-11-01 20:36
openssl3 is the highest priority. Unfortunately, we can't rollout a PyPy3.8 migration at the time because we are doing CPython3.10 right now.

**Comment by jakirkham** [comment] 2021-11-01 21:44
Yep ok prioritizing those. Mainly want to get this on the radar so we are thinking about it 😄

That said, it might be worth revisiting at the end of this month or the beginning of the next one. That would give us at least some time to produce a few PyPy packages for 3.8 before projects start dropping 3.7

**Comment by jakirkham** [comment] 2021-11-01 21:46
cc @rgommers (for awareness)

**Comment by h-vetinari** [comment] 2021-11-23 22:15
Hey all, the first numpy 1.22.0 release candidate just arrived, and it's dropping python 3.7 support, and therefore can not currently be supported with pypy in conda-forge; I realize that the CPython 3.10 migration only just started slowing down, but I thought I'd mention it.

**Comment by h-vetinari** [comment] 2021-11-27 02:03
May I try to gauge the mood for starting a pypy3.8 migration? Too early? Just a PR away?
@isuruf @mattip @beckermr

**Comment by isuruf** [comment] 2021-11-27 02:24
Too early IMO.

**Comment by mattip** [comment] 2021-12-17 11:03
The [python 310 migration](https://conda-forge.org/status/#python310) has "done (1478) in-pr (400) awaiting-pr(0) not-solvable (99) awaiting-parents (334) bot-error (16)". Is there a criteria for staging the pypy3.8 migration? We are probably about two months away from a new pypy release which will include a pypy3.9. Would you prefer to stage both pypy3.8 and pypy3.9 at once or do them one at a time?

**Comment by mattip** [comment] 2021-12-17 11:04
Or skip pypy3.8 and wait for pypy3.9 (also a valid option to reduce churn)?

**Comment by mattip** [comment] 2021-12-18 22:10
Actually, it turns out PyPy3.8 v7.3.7 has a pretty bad bug in the definition of `PyTypeObject` (see [PyPy issue 3616](https://foss.heptapod.net/pypy/pypy/-/issues/3618)): it is missing the last CPython field `tp_vectorcall` (it has an extra PyPy-specific field instead, but that is not sufficient). This will cause code built with Cython>=0.29.26 to warn about differing size of the structs (and to error on MSVC).

**Comment by mattip** [comment] 2022-01-02 08:28
Cython 0.29.27 will have a work around for the bug above.

**Comment by jakirkham** [comment] 2022-01-05 08:32
Let's bring it up at the conda-forge meeting next week.

**Comment by mattip** [comment] 2022-01-12 07:00
Have we heard of pressure from end users who would like to have pypy3.8 available (issues, requests on gitter, ...)?

If not, I would like to propose that conda-forge hold off on the migration until the next release of PyPy, which should happen in the next few weeks. The first python3.8 release has some performance regressions and bugs that will be fixed. While we could backport them as patches, I think it would be easier just to wait.

**Comment by jakirkham** [comment] 2022-01-12 07:07
Ah ok. Good to know. Still it would be good to get a sense whether we are ready to do this. That was my plan with raising this in the meeting.

Do you have any links to relevant issues that we should be waiting on?

**Comment by mattip** [comment] 2022-01-12 07:26
For release blockers, there are some open ones in [milestones for pypy 7.3.8](https://foss.heptapod.net/pypy/pypy/-/milestones/9), we have closed all the [milestones for python3.8](https://foss.heptapod.net/pypy/pypy/-/milestones/4). I am not very good about which ones are general PyPy problems across versions and which ones are 3.8-specific. You can also see there some of the completed milestones that will be part of the release.

I will be working on a more complete release note as we get closer to the release.

**Comment by jakirkham** [comment] 2022-01-12 07:32
No worries. That's already useful information.

Sounds good. Thanks Matti! 😄

**Comment by jakirkham** [comment] 2022-02-23 22:43
@mattip, just wanted to check in and see if there were any updates here 🙂

**Comment by h-vetinari** [comment] 2022-02-23 23:20
It's not far (🤞) from being in conda-forge... https://github.com/conda-forge/pypy3.6-feedstock/pull/73

**Comment by jakirkham** [comment] 2022-02-23 23:53
Ah thanks for the pointer. Was not aware of that

**Comment by h-vetinari** [comment] 2022-02-23 23:55
I guess the question now becomes: do we migrate both pypy3.8 and pypy3.9 at the same time?

**Comment by jakirkham** [comment] 2022-02-24 00:12
It's probably easier to do both at the same time as opposed to separately. Though that does meaning adding 2 new jobs everywhere as opposed to 1

However given some packages are now dropping Python 3.7 ( https://github.com/conda-forge/conda-forge.github.io/issues/1616 ) (which motivated the check-in here), perhaps the burden is less than that

**Comment by hmaarrfk** [comment] 2022-02-24 02:33
I would prefer to skip PyPy3.8 if we can. Unless there is a specific need I am missing.

**Comment by mattip** [comment] 2022-02-24 10:02
I am not sure which migration to recommend: PyPy3.8 which should be pretty solid, or PyPy3.9 which might still has some rough edges. Once the feedstock is ready, is there a way to try a few key packages before starting a conda-forge migration of all packages?

**Comment by h-vetinari** [comment] 2022-03-13 11:31
Migrator being prepared here: #2601

**Comment by hmaarrfk** [comment] 2022-08-14 21:44
I think the migration has started.

**Closed by hmaarrfk** 2022-08-14 21:44 UTC
